#!/usr/bin/env python3
"""Shared helpers for ComfyUI start/stop/daemon scripts."""

from __future__ import annotations

import os
import signal
import socket
import subprocess
import sys
import time
from pathlib import Path

COMFY_ROOT = Path(os.environ.get("COMFYUI_ROOT", "/root/ComfyUI")).resolve()
CONDA_SH = Path(os.environ.get("CONDA_SH", "/opt/miniconda3/etc/profile.d/conda.sh"))
CONDA_ENV = os.environ.get("COMFYUI_CONDA_ENV", "ComfyUI")
HOST = os.environ.get("COMFYUI_HOST", "0.0.0.0")
PORT = int(os.environ.get("COMFYUI_PORT", "8188"))

# Local runtime weights (fast disk). /workdata is backup only.
H3_MODEL_SRC = Path(os.environ.get("COMFYUI_H3_MODEL_SRC", "/root/models/MiniMax-H3-ComfyUI")).resolve()
H3_REGISTER_ROOTS = [
    COMFY_ROOT,
    Path("/workdata/ComfyUI/ComfyUI"),
]
H3_MODEL_FILES = {
    "diffusion_models": [
        "minimax_h3_ref2va_pruned_bf16.safetensors",
        "minimax_h3_fl2va_pruned_bf16.safetensors",
    ],
    "text_encoders": [
        "qwen3vl_32b_minimax_h3_bf16.safetensors",
    ],
    "vae": [
        "minimax_h3_video_vae_fp16.safetensors",
        "minimax_h3_audio_vae_fp32.safetensors",
    ],
}

RUN_DIR = COMFY_ROOT / "run"
LOG_DIR = COMFY_ROOT / "logs"
PID_FILE = RUN_DIR / "comfyui.pid"
PGID_FILE = RUN_DIR / "comfyui.pgid"
LOG_FILE = Path(os.environ.get("COMFYUI_LOG", str(LOG_DIR / "comfyui_server.log")))
MODE_FILE = RUN_DIR / "comfyui.mode"  # fg | bg


def ensure_dirs() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)


def _extra_model_paths_yaml() -> str:
    return f"""# Auto-generated by comfyui_service.register_models()
# Runtime weights: {H3_MODEL_SRC}
# /workdata is persistent backup only.

minimax_h3:
    base_path: {H3_MODEL_SRC}
    is_default: true
    diffusion_models: diffusion_models/
    text_encoders: text_encoders/
    vae: vae/

comfyui_local:
    base_path: {COMFY_ROOT}/
    checkpoints: models/checkpoints/
    configs: models/configs/
    loras: models/loras/
    vae: models/vae/
    text_encoders: |
         models/text_encoders/
         models/clip/
    diffusion_models: |
         models/unet/
         models/diffusion_models/
    clip_vision: models/clip_vision/
    embeddings: models/embeddings/
    controlnet: models/controlnet/
    upscale_models: models/upscale_models/
    audio_encoders: models/audio_encoders/
"""


def _symlink(dst: Path, src: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.is_symlink() or dst.exists():
        try:
            if dst.is_symlink() and dst.resolve() == src.resolve():
                return
        except OSError:
            pass
        dst.unlink()
    os.symlink(src, dst)


def register_models(verbose: bool = True) -> list[str]:
    """Register MiniMax-H3 weights into ComfyUI via extra_model_paths.yaml + symlinks.

    Returns list of registered model filenames. Raises if source files missing.
    """
    missing = []
    for folder, names in H3_MODEL_FILES.items():
        for name in names:
            p = H3_MODEL_SRC / folder / name
            if not p.is_file():
                missing.append(str(p))
    if missing:
        raise FileNotFoundError(
            "H3 model files missing under "
            f"{H3_MODEL_SRC}:\n  - "
            + "\n  - ".join(missing)
        )

    registered: list[str] = []
    yaml_text = _extra_model_paths_yaml()
    for root in H3_REGISTER_ROOTS:
        if not (root / "main.py").exists():
            if verbose:
                print(f"skip missing ComfyUI root: {root}")
            continue
        (root / "extra_model_paths.yaml").write_text(yaml_text, encoding="utf-8")
        if verbose:
            print(f"wrote {root / 'extra_model_paths.yaml'}")
        for folder, names in H3_MODEL_FILES.items():
            for name in names:
                src = H3_MODEL_SRC / folder / name
                _symlink(root / "models" / folder / name, src)
                if folder == "diffusion_models":
                    _symlink(root / "models" / "unet" / name, src)
                if folder == "text_encoders":
                    _symlink(root / "models" / "clip" / name, src)
                if name not in registered:
                    registered.append(name)
    if verbose:
        print("registered models:")
        for name in registered:
            print(f"  - {name}")
    return registered


def python_bin() -> Path:
    return Path(f"/opt/miniconda3/envs/{CONDA_ENV}/bin/python")


def default_accel_args() -> list[str]:
    """PPU-tuned acceleration flags.

    Priority for MiniMax-H3 on PPU (speed + quality + stability):
      1) flash-attn  (default) — verified finite on ZW810E, best balance
      2) sageattention — usually fastest; set COMFYUI_ATTN=sage
      3) xformers — fallback if COMFYUI_ATTN=xformers / unset flash+sage
    Also enable comfy-kitchen Triton (CUDA kitchen kernels are disabled on PPU).
    """
    attn = os.environ.get("COMFYUI_ATTN", "flash").strip().lower()
    args: list[str] = []
    if attn in {"flash", "flash-attn", "flash_attention"}:
        args.append("--use-flash-attention")
    elif attn in {"sage", "sageattention", "sage-attention"}:
        args.append("--use-sage-attention")
    # xformers: no flag needed; ComfyUI uses it when flash/sage not selected
    if os.environ.get("COMFYUI_ENABLE_TRITON_BACKEND", "1").strip() not in {"0", "false", "False"}:
        args.append("--enable-triton-backend")
    return args


def build_cmd(extra_args: list[str] | None = None) -> list[str]:
    py = python_bin()
    if not py.exists():
        raise FileNotFoundError(f"Conda python not found: {py}")
    if not (COMFY_ROOT / "main.py").exists():
        raise FileNotFoundError(f"ComfyUI main.py not found under {COMFY_ROOT}")
    cmd = [
        str(py),
        str(COMFY_ROOT / "main.py"),
        "--listen",
        HOST,
        "--port",
        str(PORT),
    ]
    # Built-in accel defaults first; caller/CLI extras can override later flags.
    cmd.extend(default_accel_args())
    if extra_args:
        cmd.extend(extra_args)
    return cmd


def port_open(host: str = "127.0.0.1", port: int = PORT, timeout: float = 0.5) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def read_pid() -> int | None:
    if not PID_FILE.exists():
        return None
    try:
        pid = int(PID_FILE.read_text().strip())
    except (ValueError, OSError):
        return None
    return pid if pid > 1 else None


def read_pgid() -> int | None:
    if not PGID_FILE.exists():
        return None
    try:
        pgid = int(PGID_FILE.read_text().strip())
    except (ValueError, OSError):
        return None
    return pgid if pgid > 1 else None


def pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def write_runtime(pid: int, pgid: int, mode: str) -> None:
    ensure_dirs()
    PID_FILE.write_text(f"{pid}\n")
    PGID_FILE.write_text(f"{pgid}\n")
    MODE_FILE.write_text(f"{mode}\n")


def clear_runtime() -> None:
    for p in (PID_FILE, PGID_FILE, MODE_FILE):
        try:
            p.unlink(missing_ok=True)
        except OSError:
            pass


def find_comfy_pids() -> list[int]:
    """Fallback discovery for orphaned ComfyUI main.py processes."""
    try:
        out = subprocess.check_output(["pgrep", "-af", "main.py"], text=True)
    except subprocess.CalledProcessError:
        return []
    pids: list[int] = []
    for line in out.splitlines():
        if "main.py" not in line:
            continue
        if "--port" in line and str(PORT) not in line and f"--port {PORT}" not in line:
            # keep loose match: most installs use our argv
            pass
        if "ComfyUI" in line or "main.py --listen" in line or f"--port {PORT}" in line:
            try:
                pids.append(int(line.split(None, 1)[0]))
            except ValueError:
                continue
    # de-dup while preserving order
    seen = set()
    uniq = []
    for p in pids:
        if p not in seen and p != os.getpid():
            seen.add(p)
            uniq.append(p)
    return uniq


def status_text() -> str:
    pid = read_pid()
    pgid = read_pgid()
    mode = MODE_FILE.read_text().strip() if MODE_FILE.exists() else "?"
    alive = bool(pid and pid_alive(pid))
    listening = port_open()
    lines = [
        f"root={COMFY_ROOT}",
        f"url=http://{HOST if HOST != '0.0.0.0' else '127.0.0.1'}:{PORT}",
        f"pid={pid} alive={alive}",
        f"pgid={pgid}",
        f"mode={mode}",
        f"port_{PORT}_open={listening}",
        f"log={LOG_FILE}",
    ]
    return "\n".join(lines)


def stop_services(timeout: float = 20.0) -> int:
    """Stop ComfyUI frontend+backend process tree. Returns number of signaled PIDs."""
    ensure_dirs()
    targets: list[tuple[str, int]] = []

    pgid = read_pgid()
    pid = read_pid()
    if pgid and pid_alive(pgid):
        targets.append(("pgid", pgid))
    elif pid and pid_alive(pid):
        targets.append(("pid", pid))

    for orphan in find_comfy_pids():
        targets.append(("orphan", orphan))

    # unique ids
    seen = set()
    uniq_targets = []
    for kind, value in targets:
        key = (kind, value)
        if key in seen:
            continue
        seen.add(key)
        uniq_targets.append((kind, value))

    if not uniq_targets and not port_open():
        clear_runtime()
        print("ComfyUI is not running.")
        return 0

    signaled = 0
    for kind, value in uniq_targets:
        try:
            if kind == "pgid":
                os.killpg(value, signal.SIGTERM)
            else:
                os.kill(value, signal.SIGTERM)
            signaled += 1
            print(f"sent SIGTERM to {kind}={value}")
        except ProcessLookupError:
            pass
        except PermissionError as e:
            print(f"permission error stopping {kind}={value}: {e}", file=sys.stderr)

    deadline = time.time() + timeout
    while time.time() < deadline:
        still = []
        if pgid and pid_alive(pgid):
            still.append(pgid)
        if pid and pid_alive(pid):
            still.append(pid)
        still.extend([p for p in find_comfy_pids() if pid_alive(p)])
        if not still and not port_open():
            break
        time.sleep(0.3)

    # force kill leftovers
    leftovers = []
    if pgid and pid_alive(pgid):
        leftovers.append(("pgid", pgid))
    for orphan in find_comfy_pids():
        leftovers.append(("pid", orphan))
    for kind, value in leftovers:
        try:
            if kind == "pgid":
                os.killpg(value, signal.SIGKILL)
            else:
                os.kill(value, signal.SIGKILL)
            print(f"sent SIGKILL to {kind}={value}")
            signaled += 1
        except ProcessLookupError:
            pass

    clear_runtime()
    if port_open():
        print(f"warning: port {PORT} still open after stop", file=sys.stderr)
        return signaled or 1
    print("ComfyUI stopped.")
    return signaled


def start_process(mode: str, extra_args: list[str] | None = None) -> subprocess.Popen:
    """Start ComfyUI in a new session; returns Popen. Caller manages lifecycle."""
    ensure_dirs()
    if port_open():
        raise RuntimeError(f"Port {PORT} already in use. Stop existing service first.")

    existing = read_pid()
    if existing and pid_alive(existing):
        raise RuntimeError(f"ComfyUI already running with pid={existing}")

    # Always (re)register H3 models before launch so UI can see them.
    print("Registering MiniMax-H3 models into ComfyUI...")
    register_models(verbose=True)

    cmd = build_cmd(extra_args)
    env = os.environ.copy()
    env.setdefault("PYTHONUNBUFFERED", "1")
    # PPU: NVIDIA comfy_kitchen CUDA kernels crash (rms_rope invalid argument).
    # quant_ops.py also auto-disables on PPU device name; env is belt-and-suspenders.
    env.setdefault("COMFY_KITCHEN_DISABLE_CUDA", "1")
    # Local prompt-polish LLM defaults (managed by scripts/sglang_*.py)
    env.setdefault("COMFYUI_LLM_BASE_URL", f"http://127.0.0.1:{os.environ.get('SGLANG_POLISH_PORT', '8030')}/v1")
    env.setdefault("COMFYUI_LLM_MODEL", os.environ.get("SGLANG_POLISH_MODEL_NAME", "qwen3.6-fast"))

    log_f = open(LOG_FILE, "a", encoding="utf-8", buffering=1)
    log_f.write(f"\n===== start mode={mode} at {time.strftime('%Y-%m-%d %H:%M:%S')} =====\n")
    log_f.write("cmd: " + " ".join(cmd) + "\n")
    log_f.flush()

    # New session => independent process group; survives IDE close when daemonized.
    proc = subprocess.Popen(
        cmd,
        cwd=str(COMFY_ROOT),
        env=env,
        stdout=log_f,
        stderr=subprocess.STDOUT,
        stdin=subprocess.DEVNULL,
        start_new_session=True,
    )
    pgid = os.getpgid(proc.pid)
    write_runtime(proc.pid, pgid, mode)
    return proc


def wait_until_ready(timeout: float = 120.0) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if port_open():
            return True
        pid = read_pid()
        if pid and not pid_alive(pid):
            return False
        time.sleep(0.5)
    return port_open()
